plugins {
    kotlin("jvm")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(Version.JAVA)

dependencies {
    api(Dependency.GDX)
    api(Dependency.GDX_BOX2D)
    api(Dependency.GDX_FREETYPE)
    api(Dependency.GDX_AI)
    api(Dependency.ASHLEY)
    api(Dependency.VIS_UI)
    api(Dependency.KTX_ACTORS)
    api(Dependency.KTX_AI)
    api(Dependency.KTX_APP)
    api(Dependency.KTX_ASHLEY)
    api(Dependency.KTX_ASSETS)
    api(Dependency.KTX_ASSETS_ASYNC)
    api(Dependency.KTX_ASYNC)
    api(Dependency.KTX_BOX2D)
    api(Dependency.KTX_COLLECTIONS)
    api(Dependency.KTX_FREETYPE)
    api(Dependency.KTX_FREETYPE_ASYNC)
    api(Dependency.KTX_GRAPHICS)
    api(Dependency.KTX_I18N)
    api(Dependency.KTX_INJECT)
    api(Dependency.KTX_JSON)
    api(Dependency.KTX_LOG)
    api(Dependency.KTX_MATH)
    api(Dependency.KTX_PREFERENCES)
    api(Dependency.KTX_REFLECT)
    api(Dependency.KTX_SCENE2D)
    api(Dependency.KTX_STYLE)
    api(Dependency.KTX_TILED)
    api(Dependency.KTX_VIS)
    api(Dependency.KTX_VIS_STYLE)
    api(Dependency.GSON)
}
